version: '3.4'
services:
  darts_score:
    container_name: darts_score_server
    build:
      context: .
      target: development
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./public:/app/public
      - ./src:/app/src
      - ./package.json:/app/package.json
    env_file:
      - ./.env
    tty: true
    environment:
      NODE_ENV: "development"
    depends_on:
      - mongo
  # darts_score:
  #   container_name: darts_score_server
  #   build:
  #     context: .
  #     target: production
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./data:/app/data
  #   env_file:
  #     - ./.env
  #   tty: true
  #   environment:
  #     NODE_ENV: "production"
  #     LOG_LEVEL: "info"
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo
    container_name: darts_score_mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./mongo.env
    volumes:
      - type: volume
        source: darts_score_db
        target: /data/db

volumes:
  darts_score_db:
    name: darts_score_db