name: darts-score-api

on:
  pull_request:
    branches: [ main ]

jobs:
  read_package_info:
    runs-on: ubuntu-latest
    steps:
      - uses: jaywcjlove/github-action-package@main
        name: package.json info
      - run: echo "version - ${{ steps.read_package_info.outputs.version }}"

  release-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.read_package_info.outputs.version }}
          message: '${{ steps.read_package_info.outputs.version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
  
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/darts-score-api
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ steps.read_package_info.outputs.version }}
            type=raw,value=latest
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        id: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}